name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
      - uses: LoliGothick/rustfmt-check@v0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          flags: --all
          options: --manifest-path=Cargo.toml
          args: --config-path=rustfmt.toml
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Build
        run: cargo build --verbose
